### ISSUE TITLE
Cant install harvested organ on custom race

### ISSUE THREAD

**Issue by BaalEvan** [SineSwiper/RimWorld-XenobionicPatcher#11]
EPOE-Forked + Fantasy Goblins Updated:
With Xenobionic Patcher i can't install Legs,Hands,Eyes,Nose harvested from prisoners (harvest everything) or PostMortem.
Normal prostetics works
Harvested organs works for humans

After removing Xenobionic Patcher operations are available

**Comment by SineSwiper** [comment]
Is this still a problem with the latest release?
