### ISSUE TITLE
Xenobiotic patcher doesn't patch Android Tiers properly

### ISSUE THREAD

**Issue by glencoe2004** [SineSwiper/RimWorld-XenobionicPatcher#12]
This is because some android parts have a different display name, but otherwise are identical to normal pawn parts (eg heatsink is a renamed lung, coolant pump is a renamed heart, etc.) This causes problems with the patching, which (based on the description) does not associate parts like the coolant pump with the heart.

Android parts that are named the same as a normal pawns (e.g. leg or arm) are patched correctly and do not need to be fixed.

**Comment by SineSwiper** [comment]
I might add these to the static part mapper, but I have to be careful how far I extend these kinds of mechanical "synonyms".  A "coolant pump" sounds like a heart analogue (maybe?), but a "heatsink" is more ambiguous.

It might be better to investigate the BodyPartDef tags, which has stuff like "BloodPumpingSource" and "HearingSource".

**Comment by SineSwiper** [comment]
This should be fixed in the latest version.
