### ISSUE TITLE
Xenobionic Patcher throws an error on startup with Harvest Everything!

### ISSUE THREAD

**Issue by ShadowDragon8685** [SineSwiper/RimWorld-XenobionicPatcher#14]
Xenobionic Patcher throws an error on startup with Harvest Everything! installed. I have Harvest Everything installed just before Xenobionic Patcher, and the startup log throws the following substantial error:

`[HugsLib][ERR] XenobionicPatcher caused an exception during OnDefsLoaded: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.Dictionary`2+KeyCollection+Enumerator[TKey,TValue].MoveNext () [0x00013] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at XenobionicPatcher.DefInjectors.InjectSurgeryRecipes (System.Collections.Generic.List`1[T] surgeryList, System.Collections.Generic.List`1[T] pawnList) [0x00f36] in <51b55d89af12431fa6285344fe3583b2>:0 
  at XenobionicPatcher.Base.DefsLoaded () [0x007c2] in <51b55d89af12431fa6285344fe3583b2>:0 
  at HugsLib.HugsLibController.OnDefsLoaded () [0x0001a] in <4dd8a30b2ddc479e878b55ffe02db6e8>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
HugsLib.Utils.ModLogger:ReportException (System.Exception,string,bool,string)
HugsLib.HugsLibController:OnDefsLoaded ()
(wrapper dynamic-method) HugsLib.HugsLibController:HugsLib.HugsLibController.LoadReloadInitialize_Patch1 (HugsLib.HugsLibController)
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()`

The full HugsLib output can be found [here](https://gist.github.com/HugsLibRecordKeeper/8d3fa34a42a70e121ae2a747050c8124).
I'm (trying to) use Harvest Everything![Adopted] as found [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2007485974)

**Comment by NoTouchingKids** [comment]
Same here

but it seem harmless when in game

https://gist.github.com/da0ef3474b7b4a8eab13c4a43d857b42

**Comment by SineSwiper** [comment]
I have that mod myself and I'm not seeing any issue with it.  This must have been fixed recently.
