### ISSUE TITLE
CleanupHandFootSurgeryRecipes not taking into account Shoulders

### ISSUE THREAD

**Issue by vorpal-void** [SineSwiper/RimWorld-XenobionicPatcher#15]
I'm not C# proficient, but it seems like the CleanupHandFootSurgeryRecipes should be taking into account Shoulders as well as foots and hands. Right now I'm able to install anything from "legs" operation bills into them, but not into hands (which implies cleanup is working for those)

![изображение](https://user-images.githubusercontent.com/60776130/134261483-2946f417-3057-4f4d-8c99-ef5ba4110e4c.png)

**Comment by SineSwiper** [comment]
This should be fixed now in the latest update.
