### ISSUE TITLE
Mod Incompatibility

### ISSUE THREAD

**Issue by PaZakwan** [SineSwiper/RimWorld-XenobionicPatcher#17]
Error with the mods: "A Dog Said... Animal Prosthetics","[L] House Maid Nukos" and the next options enabled: "Install Artificial Body Parts" and "Animal Surgeries -> Animals"

Error Logs: https://gist.github.com/HugsLibRecordKeeper/8d8aa9d8e7eacba8cb7652011f0413d5

**Comment by SineSwiper** [comment]
Is this still a problem with the latest release?
