### ISSUE TITLE
Pink squares when used with avali mod

### ISSUE THREAD

**Issue by Midaychi** [SineSwiper/RimWorld-XenobionicPatcher#2]
If a human spawns with avali bionics from the mod then they show up as giant pink squares.
Avali Race Mod - 1.5.1
+
LDv's Race Mods personal Graphic Retouch - for Avali

**Comment by SineSwiper** [comment]
That's a tough one.  What's likely happening is that the graphic retouch mod is only expecting Avali to have the Avali bionics, so when humans show up with Avali bionics, the mod has no icons for that combination and RimWorld defaults to a pink square.  XP would need to figure out which surgery options has graphics and remove them when applying to other pawn types.

Does it work if you remove the graphic retouch mod?

**Comment by Midaychi** [comment]
Ever since avali updated to 1.6.0 I haven't been able to trigger the squares again either with or without the graphic retouch mod. I'll keep checking but I'm pretty confused myself lol. Maybe it wasn't either mod
