### ISSUE TITLE
Mod incompatability with the new update for VFE Androids

### ISSUE THREAD

**Issue by TheReallyP** [SineSwiper/RimWorld-XenobionicPatcher#20]
I don't think anyone else reported this yet, since it worked partially for a while, but a new update(around a week ago) to the VFE Androids mod changed the androids from a vanilla xenotype category to a seperate category, breaking the game with this mod loaded. 

Game will crash whenever entering a map with both mods active. I tried several times to load previous saves and to make a new game, always resulting in a crash upon trying to enter a map. 

https://gist.github.com/TheReallyP/b2e13aebb5f867ecab06392ee018b43c

**Comment by SineSwiper** [comment]
I didn't see any crashes from my testing, but I did fix some incompatibilities with the mod.  Please try it again with the latest version.
