### ISSUE TITLE
Missing string in Keyed

### ISSUE THREAD

**Issue by kamikadza13** [SineSwiper/RimWorld-XenobionicPatcher#21]
Hello. Can you add "Add hediff" into Keyed for translation, that option is located in "Surgery category"?
![](https://i.ibb.co/gz8n1ht/Screenshot-4.png)

For example that operation category is shown for vasectomy surgery

**Comment by SineSwiper** [comment]
Sure.  I've fixed it in the XML and I'll get it pushed out in the next release.
