### ISSUE TITLE
Incompatibility with Vanilla Factions Expanded - Pirates 

### ISSUE THREAD

**Issue by wzhidao278** [SineSwiper/RimWorld-XenobionicPatcher#24]
i can't install bionics on animals,this my mod.
![20240524060622](https://github.com/SineSwiper/RimWorld-XenobionicPatcher/assets/170678704/e7484526-f330-4c14-8105-a6b4008e1294),here's the log:
[Uploading Exception filling tab RimWorld.ITab.log…]()

**Comment by MoYuQueen** [comment]
sry,is this
[Exception filling tab RimWorld.ITab.log](https://github.com/SineSwiper/RimWorld-XenobionicPatcher/files/15424486/Exception.filling.tab.RimWorld.ITab.log)

**Comment by SineSwiper** [comment]
`VFEPirates.RecipeWorker_WarcasketRemoval.AvailableOnNow` was causing problems, due to a lack of a `pawn.apparel` check.  I removed `RecipeWorker_WarcasketRemoval` as a modded class in the latest release, since we can't control which pawns get the warcasket, anyway.
