### ISSUE TITLE
Update to 1.1 is NOT backward compatible

### ISSUE THREAD

**Issue by Staz73** [SineSwiper/RimWorld-XenobionicPatcher#3]
Harmony core lib does not work in Rimworld 1.0, so update of XBP will no longer work with Rimworld 1.0.

**Comment by SineSwiper** [comment]
Harmony core library has always been a part of RimWorld for just about every mod.  It's just that Brrrainz released it as a workshop item to keep track of versioning.

[More details on his mod page](https://steamcommunity.com/workshop/filedetails/?id=2009463077)
