### ISSUE TITLE
Atispec from Alpha animals some parts not changeable

### ISSUE THREAD

**Issue by Pultex** [SineSwiper/RimWorld-XenobionicPatcher#6]
Not sure if there is a form to this

Alpha animals AA_Atispec has 'left claw' and <linkedBodyPartsGroup>FrontLeftClaws</linkedBodyPartsGroup>
do these not work for the hand bionic

I thought that hands and claws could be exchanged or is this and Alpha animals limitation

Not sure if this is being worked on anymore just thought I'd ask

**Comment by SineSwiper** [comment]
Claws are part of the static part mapper, linked with hand surgeries, and directional wording like "left" or "front" shouldn't interfere with it.  Is this still a problem?
