### ISSUE TITLE
Null Reference Exception during surgery cleanup

### ISSUE THREAD

**Issue by AmericanWeeb** [SineSwiper/RimWorld-XenobionicPatcher#7]
[HugsLib][ERR] XenobionicPatcher caused an exception during OnDefsLoaded: System.NullReferenceException: Object reference not set to an instance of an object
  at XenobionicPatcher.DefInjectors.CleanupSurgeryRecipes (System.Collections.Generic.List`1[T] surgeryList, System.Collections.Generic.List`1[T] pawnList) [0x002c1] in <b538e4473fd143b78013f4716f95b49c>:0 
  at (wrapper dynamic-method) XenobionicPatcher.Base.XenobionicPatcher.Base.DefsLoaded_Patch2(XenobionicPatcher.Base)
  at HugsLib.HugsLibController.OnDefsLoaded () [0x0001a] in <e4b32d84f714481f906e5eea5e560e3b>:0 
Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
HugsLib.Utils.ModLogger:ReportException(Exception, String, Boolean, String)
HugsLib.HugsLibController:OnDefsLoaded()
HugsLib.HugsLibController:HugsLib.HugsLibController.LoadReloadInitialize_Patch2(HugsLibController)
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

I am unable to post full logs due to timeout, my debug log is tens of thousands of lines long due to limit testing a near 1000 mod mod pack. This is my only Error remaining and I can't seem to figure it out.

**Comment by SineSwiper** [comment]
I've cleaned up most of the NPEs a while ago.  If you're still encountering issues, please open another issue.
