### ISSUE TITLE
Cleaning up hand/foot surgeries for Remove hand talon, but ended up removing all the body parts!

### ISSUE THREAD

**Issue by Zagnard** [SineSwiper/RimWorld-XenobionicPatcher#8]
Greetings. Seems like I cam across a small issue. If you may, check line 3425: https://gist.github.com/HugsLibRecordKeeper/a5db0a9dfd9748daeeced25dc94591b3

Info not on the log:
[XenobionicPatcher][ERR] Cleaning up hand/foot surgeries for Remove hand talon, but ended up removing all the body parts!
Verse.Log:Error(String, Boolean)
HugsLib.Utils.ModLogger:Error(String, Object[])
XenobionicPatcher.DefInjectors:CleanupHandFootSurgeryRecipes(List`1)
XenobionicPatcher.Base:DefsLoaded()
HugsLib.HugsLibController:OnDefsLoaded()
HugsLib.HugsLibController:HugsLib.HugsLibController.LoadReloadInitialize_Patch1(HugsLibController)
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by SineSwiper** [comment]
Is this still a problem with the latest release?
